### ISSUE TITLE
Remaining problems in AdaPT

### ISSUE THREAD

**Issue by Enigmatisms** [Enigmatisms/AdaPT#3]
Currently, BDPT is already implemented therefore I might slow down the development on this repo. Yet, some **problems** remain in the repo:
- Specular material rendering result inconsistency. When rendering mirror reflection / Frensel specular effect, BDPT tends to have darker (surface), while other non-specular parts are intact. BDPT rendering is not consistent with PT rendering (which looks better), nor is the result consistent with pbrt-v3 or Mitsuba0.6 (though, pbrt-v3/4 can't render a noise free image of `csphere/single-ball.xml`, Mitsuba0.6 itself doesn't look as good as pt rendering). This should be taken care of.
- Anisotropic BRDF burst noise. For `FrenselBlend` BRDF, there will be shot noises on the image. I suspect it's the problem of PDF calculation (MIS weight)
- Taichi function inlining introduces long JIT compilation time for BDPT since BDPT is lengthy and its member functions usually have complicated parameter. This should be optimized.
- VPT / volumetric BDPT seems to be fixed already, but the brightness seems not consistent with PT (no extensive experiment shows this yet, I just remember this vaguely). Brightness is not a huge problem, though.

---

New features that can be added:
- [ ] Since BDPT is added, we can implement collimated light and spot light in the repo.
- [ ] Scene visualizer should first experiment on mouse control (for view manipulation purpose). Since AdaPT is a real time rendering platform (on GPU and without BDPT, BDPT can only reach 12-16 fps, yet some scene for PT can achieve 120+fps), we can consider changing the camera extrinsic and other configs on the fly.
- [ ] More BSDF (for different transmission / reflection effect), this is relatively easy.
- [ ] Metropolis light transport can be added to further boost the rendering (low priority).

**Comment by Enigmatisms** [comment]
Oh, don't forget acceleration structure like BVH / KD-tree implementation.

**Comment by Enigmatisms** [comment]
Pull request #4 seems to have fixed some of the problems mentioned above:
-  Specular material rendering result inconsistency. The current problem of specular path is about caustics path (SDS), which slows down the convergence. Yet the problem of the material being darker is fixed.
- Anisotropic BRDF burst noise. This was due to the wrong caculation of PDF and we failed to do the correct diffusive / specular part sampling.
- VPT brightness consistency with PT. Now the sampled vertex can be correctly updated, therefore I think the brightness consistency (brightness loss problem) might be fixed already? No comparison is provided, though. 

About JIT and code optimization, these stuff should be done in the future when I have time.

**Comment by Enigmatisms** [comment]
Currently, collimated light and transient rendering are completed (see PR #6 and the subsequent commits). It can be observed that the transient rendering output worse simulations as time progresses (lack of samples, according to Jarabo et al. 2014).

**Comment by Enigmatisms** [comment]
- BVH and acceleration structure should be implemented.
- Mode `Transient Lit` (camera unwarped mode) is not correct.

**Comment by Enigmatisms** [comment]
BVH acceleration structure is on going but the current solution is suboptimal, since stack is not easy to implement in Taichi lang (actually, dynamic snode would help). In this sense, the code has some parts (non-trivial) that can be improved with dynamic snode.

**Comment by jchinniah** [comment]
I am getting errors

from la.cam_transform import *
from emitters.point import PointSource
from tracer.tracer_base import TracerBase

from parser.obj_desc import ObjDescriptor
from parser.xml_parser import mitsuba_parsing

Taichi] version 1.5.0, llvm 15.0.1, commit 7b885c28, win, python 3.10.11
Traceback (most recent call last):
  File "d:\Python_RayTracing\AdaPT-1.2.1\tracer\path_tracer.py", line 18, in <module>
    from la.cam_transform import *
ModuleNotFoundError: No module named 'la'

**Comment by zubairdroid** [comment]
scene_viz.py doesnt work
  File "C:\Users\zdroid\Downloads\AdaPT-master\AdaPT-master - Copy\scene_viz.py", line 212, in <module>
    viz.render()
  File "C:\Users\zdroid\miniconda3\envs\AdaPT\lib\site-packages\taichi\lang\kernel_impl.py", line 1037, in __call__
    raise type(e)('\n' + str(e)) from None
taichi.lang.exception.TaichiCompilationError:
File "C:\Users\zdroid\Downloads\AdaPT-master\AdaPT-master - Copy\scene_viz.py", line 124, in render:
            obj_id, normal, _ = self.ray_intersect(ray, self.cam_t[None])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\zdroid\Downloads\AdaPT-master\AdaPT-master - Copy\tracer\tracer_base.py", line 138, in ray_intersect:
            start_id  = self.obj_info[aabb_idx, 0]
                        ^^^^^^^^^^^^^
Traceback (most recent call last):
  File "C:\Users\zdroid\miniconda3\envs\AdaPT\lib\site-packages\taichi\lang\ast\ast_transformer_utils.py", line 25, in __call__
    return method(ctx, node)
  File "C:\Users\zdroid\miniconda3\envs\AdaPT\lib\site-packages\taichi\lang\ast\ast_transformer.py", line 862, in build_Attribute
    node.ptr = getattr(node.value.ptr, node.attr)
  File "C:\Users\zdroid\miniconda3\envs\AdaPT\lib\site-packages\taichi\lang\kernel_impl.py", line 1079, in _getattr
    x = super(cls, self).__getattribute__(item)
  File "C:\Users\zdroid\miniconda3\envs\AdaPT\lib\site-packages\taichi\lang\kernel_impl.py", line 1079, in _getattr
    x = super(cls, self).__getattribute__(item)
AttributeError: 'Visualizer' object has no attribute 'obj_info'
GLFW Error 65537: The GLFW library is not initialized

**Comment by Enigmatisms** [comment]
@zubairdroid You can open an independent issue and provide your runtime environment setup. As for the problem related to `scene_viz.py`, this script has not been updated for a long time, since this is not for rendering but for visualizing the scene configuration. To run the renderer, please refer to #14, see the comment of mine in that issue. I'll be checking the problems of `scene_viz.py`

**Comment by Enigmatisms** [comment]
@zubairdroid The comment here will be deleted after you open an independent issue, since this issue is for suggestions but not bug reporting or making questions.

**Comment by Enigmatisms** [comment]
@zubairdroid This is indeed a bug, due to the update of BVH. The TraceBase class is not compatible with the old Visualizer class. I didn't update the code in `scene_viz.py`, being working on it.

**Comment by Enigmatisms** [comment]
Creating an issue for this problem.

**Comment by Enigmatisms** [comment]
@zubairdroid Check #15 for more updates on this issue. Yet this does not prevent you from using this renderer, since this is not a part of renderer main logic.

**Comment by Enigmatisms** [comment]
Problem mentioned is now fixed. Related comments will be deleted in 9 hours.

**Comment by Enigmatisms** [comment]
Staled tasks.
